name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: pip install uv && uv pip install -e ".[dev]"

      - name: Run lint
        run: uv run ruff check .

      - name: Run type check
        run: uv run mypy fastapi_tenants

      - name: Run tests
        run: uv run pytest --cov=fastapi_tenants --cov-report=xml
